### ISSUE TITLE
MapView not rerendering

### ISSUE THREAD

**Issue by daveed80** [Esri/react-arcgis#102]
I have a component I've created whos render method is below. This component is composed of the ArcGIS `<Map />` component. All works as expected on the first render. However, when I set a new x/y in my component and pass down the new x/y props to the `<Map />` component, thus causing a re-render/new `viewProperties`, the map doesn't change/appear to re-render.

I'm sure I'm using the api incorrectly, or am just missing something in general, but any help would be greatly appreciated! There's not much else going on in my component, but please let me know if you need to see the full component code.

I should add that `onLoad `and `onFail ` don't re-fire as well, I'm assuming because the `<Map /> `is already loaded into the DOM. So that may be the answer, to unload the map in some fashion, or possibly another approach altogether.

Thanks again!

```
render() {
        const y = this.props.y || -82.801228000;
        const x = this.props.x || 27.961938000;
                      
        return ( 
            <Map 
                onLoad={this.handleMapLoadSuccess} 
                onFail={this.handleMapLoadFail}
                mapProperties={{ basemap: 'streets' }}
                viewProperties={{
                    center: [y, x],
                    zoom: 15
                }}
        />
    )}
```

**Comment by daveed80** [comment]
I should add that `onLoad `and `onFail `doesn't re-fire as well, I'm assuming because the `<Map />` is already loaded into the `DOM`. So that may be the answer, to unload the map in some fashion, or possibly another approach altogether.

Thanks again!

**Comment by daveed80** [comment]
Entire component code for completeness....

```
import React from 'react';
import { Map } from '@esri/react-arcgis';
import { loadModules } from 'esri-loader';

export default class ChecklistMap extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            map: null,
            view: null
        };
    }

    handleMapLoadFail = (e) => {
        console.log(e);
    }
       
    handleMapLoadSuccess = (map, view) => {
        loadModules(["esri/Graphic", "esri/geometry/support/webMercatorUtils", "dojo/domReady!"])
        .then(([Graphic, webMercatorUtils]) => {

            var marker = {
                type: "picture-marker",
                url:
                  "https://arcgis.github.io/arcgis-samples-javascript/sample-data/cat3.png",
                width: 46,
                height: 46
              };
          
            view.on("click", (evt) => {
              var mp = webMercatorUtils.webMercatorToGeographic(evt.mapPoint);
              view.graphics.removeAll();
              view.graphics.add(new Graphic(evt.mapPoint, marker));
              this.props.onMapClick({ x: mp.x, y: mp.y });
            });

        });   
        this.setState(() => ({ map, view }));
    }
    
    render() {
        const y = this.props.y || -82.801228000;
        const x = this.props.x || 27.961938000;
                      
        return ( 
            <Map 
                onLoad={this.handleMapLoadSuccess} 
                onFail={this.handleMapLoadFail}
                mapProperties={{ basemap: 'streets' }}
                viewProperties={{
                    center: [y, x],
                    zoom: 15
                }}
        />
    )}
}
```

**Comment by nicksenger** [comment]
In this case what you need to do is get a reference to the JS API view instance through `onLoad`, then interact with the instance directly to update the center position etc in something like `componentDidUpdate`

**Comment by daveed80** [comment]
Gotcha, thanks @nicksenger .  Overall, is what I've done above considered a legit approach, or would you suggest an alternative?

**Comment by nicksenger** [comment]
From a quick look it seems like a legit approach to me. The only thing that sticks out is trying to control x,y on the map like that. After the initial render when the map instance is created, updating the props passed to the `Map` component wont really do anything. This is by design since v2, when I realized it is not really possible to make your app the single source of truth about the map's state.

It's unfortunate because what you've written  seems intuitive for a react app, but if you go down that road you will end up with 2 sources of truth for the map -- one in your app and one in the JS API itself.

**Comment by daveed80** [comment]
Solved
