### ISSUE TITLE
Demo app doesn't load with following error

### ISSUE THREAD

**Issue by rpateld** [Esri/react-arcgis#128]
![image](https://user-images.githubusercontent.com/56134077/66620823-eaa50c00-ebaf-11e9-9e65-13dd505e1956.png)

**Comment by rpateld** [comment]
![image](https://user-images.githubusercontent.com/56134077/66667456-0ac0e380-ec21-11e9-9934-0477ee36ef4c.png)

**Comment by tomwayson** [comment]
I just pulled the latest, ran the demo app, and it works fine for me. What version of the code are you on? Did you make changes? What browser (looks like Chrome)?

**Comment by rpateld** [comment]
Thanks for prompt reply. I just re installed demo dependency and tried again and it has been started working.
