### ISSUE TITLE
Sketch widget component

### ISSUE THREAD

**Issue by rpatelcode** [Esri/react-arcgis#131]
Can you please add one more demo for the Sketch widget component?

example link is here https://developers.arcgis.com/javascript/latest/sample-code/sketch-geometries/index.html

**Comment by tomwayson** [comment]
There is no sketch widget component in this library. Are you asking us to add one? We are not taking requests for components to build. If someone has built one for their own purpose and wants to share it we can help them figure out the best way to do that.

It sounds like from #125 that @tomrussell has created one that at least works at least w/ 2D MapViews. I encourage you to ask him to share his component.

**Comment by tomwayson** [comment]
Resolved in https://github.com/Esri/react-arcgis/issues/125#issuecomment-542022826
