### ISSUE TITLE
Unable to import the Point, GraphicsLayer, webMercatorUtils from the esri.

### ISSUE THREAD

**Issue by sankargflexicious** [Esri/react-arcgis#132]
Issue: Unable to import the Point, GraphicsLayer, webMercatorUtils from the esri.

code snippet:

```
import { Map } from "@esri/react-arcgis";
import { GraphicLayer } from '@esri/react-arcgis/layers/GraphicsLayer';
import {webMercatorUtils} from '@esri/react-arcgis/geometry/webMercatorUtils';
import {Point} from '@esri/react-arcgis/geometry/Point';

mapMaker = () => {
  const { mapData} = this.props;

  if(mapData.length > 0 ){
      let map = new Map();
      map.removeAllLayers();
      let graphicsLayer = new GraphicLayer();
      map.addLayer(graphicsLayer);

      for(var index=0; index<mapData.length; index++){
        const data= mapData[index];

        if(data.latitude !== '0' && data.latitude !== null && data.latitude !== '' && !NaN(Number(data.latitude)) &&
        data.longitude !== '0' && data.longitude !== null && data.longitude !== '' && !NaN(Number(data.longitude))){
          this.createMarker(data);
        } 
      }
  }
}

createMarker = (data) => {
  const conversionToMap = webMercatorUtils.geographicToWebMercator(
    new Point(Number(data.longitude), Number(data.latitude))
  );

  const dataMap = new Point(conversionToMap.x, conversionToMap.y);
  return dataMap ;
}

```

This is my snippet of code But not able to import the Point, GraphicsLayer, webMercatorUtils. How can I import it?

getting error:
Module not found: Can't resolve '@esri/react-arcgis/geometry/Point'

Version used:
@esri/react-arcgis": "^4.0.0",
"react": "^16.7.0",
"react-dom": "^16.7.0",

Can anyone suggest me?

**Comment by gavinr** [comment]
@sankargflexicious please read the [`Advanced Usage` area of the README.md](https://github.com/Esri/react-arcgis#advanced-usage) - to load in modules you need to use `loadModules` --

![image](https://user-images.githubusercontent.com/209355/66772732-0a278780-ee83-11e9-82e7-215d3e2b63e2.png)

**Comment by tomrussell** [comment]
@sankargflexicious check out the example sandbox in my comment https://github.com/Esri/react-arcgis/issues/125#issuecomment-542022826

**Comment by sankargflexicious** [comment]
@tomrussell Its working fine now. Thank you.
