### ISSUE TITLE
How to display a point in a Scene

### ISSUE THREAD

**Issue by vitorbertolucci** [Esri/react-arcgis#156]
I don't know if it is the correct place to get this kind of help since it's not a bug report. If not, I'd appreciate if someone could point me somewhere appropriate.

I'm displaying a Scene with the center specified via props and I'm trying to place a Point to mark this center:

```
<div style={styles.sceneContainer}>
          <Scene
            style={styles.scene}
            mapProperties={{ basemap: "hybrid" }}
            viewProperties={{
              center: [content.Longitude, content.Latitude],
              ui: {
                components: ["attribution"]
              },
              zoom: 17
            }}
          >
            <EsriPoint
              latitude={content.Latitude}
              longitude={content.Longitude}
            />
          </Scene>
        </div>
```

As you can see I tryied writing a component to render the point using esri-loader, but that's the farther I could go:

```
import React from "react";
import { loadModules } from "esri-loader";

export const EsriPoint = ({ map, view, latitude, longitude }) => {
  loadModules(["esri/geometry/Point"])
    .then(([Point]) => {
      const point = new Point(longitude, latitude);
      return point;
    })
    .then(point => console.log(point));

  return null;
}
```

I'm not sure what I should do with the value I get from new Point. ESRI's documentation wasn't clear enough for me.

Could someone enlighten me on how to properly use the loadModules function in this case?

**Comment by gavinr** [comment]
1. Follow the instructions in the readme under `If you want to access the map and view instances directly after they are loaded, pass in an onLoad handler`
2. In your onLoad handler, you have access to the `map` object. Use that, coupled with the `loadModules` pattern you have above, to add a GraphicsLayer to the map and a graphic to the GraphicsLayer, like in this sample: https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=graphics-basic-3d
  ![image](https://user-images.githubusercontent.com/209355/68244043-853f1200-ffd9-11e9-914b-2b353457a2e8.png)

**Comment by vitorbertolucci** [comment]
Thank you very much for your answer, I was now able to achieve what I needed. That's the end result of my code just in case it may help someone:

handleMapLoad method:
```const handleMapLoad = (map, longitude, latitude) => {
  loadModules(["esri/layers/GraphicsLayer", "esri/Graphic"]).then(
    ([GraphicsLayer, Graphic]) => {
      const graphicsLayer = new GraphicsLayer();
      map.add(graphicsLayer);

      // London
      const point = {
        type: "point",
        latitude,
        longitude
      };

      const markerSymbol = {
        type: "simple-marker",
        color: [226, 119, 40],
        outline: {
          color: [255, 255, 255],
          width: 2
        }
      };

      const pointGraphic = new Graphic({
        geometry: point,
        symbol: markerSymbol
      });

      graphicsLayer.add(pointGraphic);
    }
  );
};```

Scene div
```
<div style={styles.sceneContainer}>
          <Scene
            style={styles.scene}
            mapProperties={{ basemap: "hybrid" }}
            viewProperties={{
              center: [content.Longitude, content.Latitude],
              ui: {
                components: ["attribution"]
              },
              zoom: 17
            }}
            onLoad={map =>
              handleMapLoad(map, content.Longitude, content.Latitude)
            }
          />
        </div>
```
