### ISSUE TITLE
How to Zoom Using State Hooks

### ISSUE THREAD

**Issue by pegues** [Esri/react-arcgis#169]
I have a problem with two things. 1. I'm setting the initial zoom on page load with a stateHook value. 2. I'm not able to increase or decrease the zoom level with a click event on custom zoom buttons. Any help is very appreciated:

```
import React, { useState } from 'react';
import { Map } from '@esri/react-arcgis';

const Dashboard = (props) => {
	const [zoomLevel,setZoomLevel] = useState(3);
	
    const zoomIncrement = () => {
        setZoomLevel(zoomLevel + 1);
    }

    const zoomDecrement = () => {
        setZoomLevel(zoomLevel - 1);
    }
	
    return ( 
        <div style={{ width: '100vw', height: '100vh'}}>
            <Map
                id="12345"
                class="map"
                mapProperties={{
                    basemap: 'gray-vector',
                }} 
                viewProperties={{
                    center: [-98.5795, 39.8283],
                    zoom: {zoomLevel},
                    ui: {
                        components: ["attribution"] // empty the UI, except for attribution
                    }
                }}
                >
            </Map>
        </div>
    );
 } 
```

**Comment by tomwayson** [comment]
The `<Map/>` component doesn't provide anything like a `zoom` property that you can use to update the map's zoom level from outside the component.

You can either use the `onLoad` property to get a reference to the `view` and then update it when state changes, or [write a custom component](https://github.com/Esri/react-arcgis#creating-your-own-components) that has a `zoom` property you can pass in and then use to update the map when the state changes.

`viewProperties` are only for _initializing_ the view. So, you can set the the initial zoom, but it won't update if you change it.  It looks like the reason that didn't work for you above is that your JSX is invalid. You would have had to do something like:

```js
const [zoomLevel,setZoomLevel] = useState(3);
const viewProperties = {
  center: [-98.5795, 39.8283],
  zoom: zoomLevel,
  ui: {
    components: ["attribution"] // empty the UI, except for attribution
  }
};
```

then `viewProperties={viewProperties}` in your `return`.

You should be able to couple that w/ `onLoad` to do what you want.

**Comment by tomwayson** [comment]
Closing as we are archiving this repo
