### ISSUE TITLE
Map zooming up infinitely

### ISSUE THREAD

**Issue by shamsheertp** [Esri/react-arcgis#175]
Dear Team I have problem with this package , when i run this program i get loading issue its like infinity Zoom Loop 

Here i attached the  sandbox link 
https://codesandbox.io/s/fancy-meadow-wr4f2?fontsize=14&hidenavigation=1&theme=dark

thank you

**Comment by gavinr** [comment]
Add the following to your `styles.css`:

```
html,
body,
#root {
  height: 100%;
  width: 100%;
  margin: 0px;
}
```

Additionally, it does not look like you're loading the ArcGIS API styles. Please note:

> IMPORTANT: You must load ArcGIS API styles before using the components in this library. The snippets below assume you've already used one of the ways that esri-loader provides you with to load the ArcGIS API CSS.
https://github.com/Esri/react-arcgis#basic-usage
