### ISSUE TITLE
"ArcGIS API failed to load" Due to map_2.load(). otherwise is not a function

### ISSUE THREAD

**Issue by prudhvi-rajkumar** [Esri/react-arcgis#180]
**This issue is happening in this code block:**
```javascript
map_2.load().then(function () {
                    return map_2.basemap.load();
                })
                    .then(function () {
                    var allLayers = map_2.allLayers;
                    var promises = allLayers.map(function (layer) { return layer.load(); });
                    return all(promises.toArray());
                })
                    .then(function () {
                    var view = new ViewConstructor(__assign({ container: containerId, map: map_2 }, props.viewProperties));
                    Object.keys(eventMap).forEach(function (key) {
                        if (props[key]) {
                            view.on(eventMap[key], props[key]);
                        }
                    });
                    resolve({ map: map_2, view: view });
                }).otherwise(function (err) {
                    reject(err);
                });
```
The last block of otherwise is causing the error, as it is not catching the promise to reject it back. I have found that in your pull request, but not moved to the release. Could you help us in using the WebScene?

**Comment by gavinr** [comment]
@prudhvi-rajkumar which pull request are you referring to?

**Comment by prudhvi-rajkumar** [comment]
Oh sorry, not pull request, on 13th April commit with dda944664787af96e0ab528b098382f1b5e2fa0c, made the file changes from .otherwise() to .catch(), but didn't rolled out to the release. This results in ArcGIS API failed to load the message I'm getting when I'm using Web scene.

**Comment by prudhvi-rajkumar** [comment]
May I get any help on this?

**Comment by gavinr** [comment]
@sevenninety @prudhvi-rajkumar  The `otherwise` vs `catch` changes from #178 were released in v5.1.0 - please test and let us know if there are any issues. Thanks!

**Comment by kkarkos** [comment]
This is still happening with WebScene. No issues with Scene.

Also reported here: https://github.com/Esri/react-arcgis/issues/54

**Comment by gavinr** [comment]
@kkarkos thanks for the report. I'm not totally sure this is the same issue (Even though same error message). Could be the same, just not sure - could you please open a new issue with a reproducible test case on the latest release so we can look into it? Thanks!
