### ISSUE TITLE
Using a custom basemap

### ISSUE THREAD

**Issue by avrilanne** [Esri/react-arcgis#202]
Is there support for a custom basemap or a way to change the color of a basemap?

re. https://developers.arcgis.com/javascript/latest/sample-code/basemap-custom/

```
      mapProperties={{
        basemap: 'gray-vector'
      }}
```

**Comment by andygup** [comment]
Sure is: https://developers.arcgis.com/documentation/vector-tile-style-editor/  and here's a tutorial: https://developers.arcgis.com/javascript/latest/display-a-custom-basemap-style/

**Comment by avrilanne** [comment]
Thank you @andygup !
