### ISSUE TITLE
Uncaught ReferenceError: require is not defined And Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'on')

### ISSUE THREAD

**Issue by RonaldAroyo** [Esri/react-arcgis#224]
Why is it I am having this kind of error? I imported what needs tobe imported **npm i esri-loader-hooks, npm i esri-loader, npm i arcgis-js-api,**

```
import React from 'react';
import Map from '../../component/Map/Map.js'
const HomePage = () => {
  return (
    <div>
      <Map/>
    </div>
  );
};

export default HomePage;
```
component/Map/Map.js

```
import React , {useRef,useEffect} from 'react';
import {loadModules} from "esri-loader";


function Map() {
    const MapElement=useRef(null)
    useEffect(()=>{
        let view;

    loadModules(["esri/views/MapView", "esri/WebMap"],{
        css:true
    }).then(([MapView, WebMap])=>{
        const webmap= new WebMap({
            basemap:'topo-vector'
        })
        view = new MapView({
            map:webmap,
            center:[],
            zoom:8,
            container:MapElement.current
        })
    })
    return()=>{
        if(!!view){
            view.destroy()
            view=null
        }
    }
    })
    return (
        <div style={{height:800}} ref={MapElement}>
            
        </div>
    )
}

export default Map
```

error

<img width="496" alt="image" src="https://user-images.githubusercontent.com/53855815/144346261-555d7273-8dea-443b-9f3e-884d3171fff6.png">

**Comment by tomwayson** [comment]
@RonaldAroyo - it doesn't look like your example pertains to this repository. You should not need react-arcgis _and_ esri-loader-hooks - you would use one or the other, and it doesn't look like you are using either in your sample above. You definitely do not need arcgis-js-api.

I'm closing this issue b/c we are archiving this repository - if you still need help w/ the above issue, please open an issue on the esri-loader repository.
