### ISSUE TITLE
Update to support react v17+ and possibly react v18+

### ISSUE THREAD

**Issue by terwort** [Esri/react-arcgis#232]
My project has peer dependencies with react v17+, but this package only has 16+. Could we update this project to support react v17+?

Also, react just announced v18. Could this project also be updated to support that one as well?

Thanks!

![image](https://user-images.githubusercontent.com/37204984/160665205-c6fc4f97-59c3-4047-a681-c6f845365446.png)

**Comment by gavinr** [comment]
We added the [`^16`](https://github.com/Esri/react-arcgis/blob/3cd249707abed01ffa42f7b239270484341c773c/package.json#L67) in #100. Before it was `*` : https://github.com/Esri/react-arcgis/pull/100/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R62 ... seems to me like `*` is more flexible because it would allow you to use any version of react? @tomwayson any thoughts?

**Comment by tomwayson** [comment]
The peerDependencies should reflect what this project actually works with. I doubt it works w/ all versions of React, so * is not correct.

if someone could try it w/ 17 and verify it works, then we can update the peer dep to  `"16 || 17"`. Ditto for 18.

That said, you should probably just use [@arcgis/core](https://www.npmjs.com/package/@arcgis/core) or [esri-loader](https://github.com/Esri/esri-loader) directly in your react app.

**Comment by tsarapke** [comment]
We using react-arcgis with React 17 from the moment of it release. It about 2 years. And we don't found any issues with it. More over, as I can see from source code of react-arcgis, there is absolutely nothing that can be affected by React 18. Most of components just are stateless functions. 2 components are class components, but they use such life-cycle methods that supported by React 18. There is just nothing used that could be affected by React 17 or React 18.

**Comment by tomwayson** [comment]
thanks @tsarapke.

@terwot I would accept a pull request that updates the react and react-dom `peerDependencies` to `"16 || 17 || 18"` and the `devDependencies` to `"^18.0.0"`.

**Comment by tsarapke** [comment]
@tomwayson, here is PR that updates support of latest React: #234

**Comment by tomwayson** [comment]
This is released in 5.2.0 https://github.com/Esri/react-arcgis/releases/tag/5.2.0
