### ISSUE TITLE
"ArcGIS API failed to load" Due to view_1.then is not a function

### ISSUE THREAD

**Issue by rconard** [Esri/react-arcgis#54]
A dependency seems to have changed since I last did an _npm install_ (I believe on 4/24) that is now causing *react-arcgis* to fail.

## This issue is happening in this code block:
Lines 26 to 50 from _react-arcgis/dist/esm/components/ArcComposites.js_
```export var MapBase = function (props) { return (React.createElement(ArcView, __assign({}, props, { loadMap: function (_a, containerId) {  
        var Map = _a[0], View = _a[1];  
        var mapData = new Promise(function (resolve, reject) {  
            try {  
                var map_1 = new Map(props.mapProperties); // Make the map  
                var viewProperties = __assign({ map: map_1, container: containerId }, props.viewProperties);  
                var view_1 = new View(viewProperties); // Make the view  
                var typedView_1 = view_1;  
                Object.keys(eventMap).forEach(function (key) {  
                    if (props[key]) {  
                        typedView_1.on(eventMap[key], props[key]);  
                    }  
                });  
                view_1.then(function () {  
                    resolve({ map: map_1, view: view_1 });  
                }, function (err) {  
                    reject(err);  
                });  
            }  
            catch (err) {  
                reject(err);  
            }  
        });  
        return mapData;  
    } }))); };
```

## The Issue
The exception is being caught on line 51 (of dist file) with _TypeError: view_1.then is not a function_:
![image](https://user-images.githubusercontent.com/16137199/39372713-297d9c5c-4a13-11e8-882d-faabeb4c3f63.png)

I've been digging to find where the issue is originating, but I'm stumped. My code worked an hour ago, and it's now throwing this exception for both Scene and Map Views. It looks like *esri-loader* updated from 4.6 to 4.7 as the default build in the last few days, but I'm not thinking that this is the most likely culprit.

It seems that View was previously returning a Promise but is now just returning an object? It doesn't appear that Promise support is the underlying issue as the Promise was created on line 33 just fine (and the exception is being thrown within a Promise).

Do any ideas come to mind?

P.S. This is a fabulous wrapper for the Esri API. Thank you!

**Comment by tmcgee** [comment]
@rconard I saw this yesterday as well with react-arcgis v3.21 and arcgis JS 4.7. Adding react-arcgis to my React app (I use `yarn add react-arcgis@3.2.1`), it appears to me that the built JavaScript file installed in `node_modules/react-arcgis/dist` directory do not match the TypeScript file source in the `src` directory. The JS files use `then` but the TS files use `when` (a change at version 3.2.1). As a quick test to work-around this, I switched `then` to `when` in the JS files and it worked again. This mismatch looks to have occurred in the publishing to npm for version 3.2.1. Until @nicksenger looks into this, you can build the JS locally or make the same changes I made.

**Comment by nicksenger** [comment]
@tmcgee @rconard  I just noticed the same thing. Apologies for that, somehow the built code from the last update seems to have not been published! 😢 Unfortunate mistake there.

I'll have an update this afternoon which addresses this and some other things.

**Comment by tmcgee** [comment]
@nicksenger 3.3.0 is working for me. Thanks for the quick response!

**Comment by prudhvi-rajkumar** [comment]
I have a similar issue like this on the same file where 
```javascript
map_2.load().then(function () {
                    return map_2.basemap.load();
                })
                    .then(function () {
                    var allLayers = map_2.allLayers;
                    var promises = allLayers.map(function (layer) { return layer.load(); });
                    return all(promises.toArray());
                })
                    .then(function () {
                    var view = new ViewConstructor(__assign({ container: containerId, map: map_2 }, props.viewProperties));
                    Object.keys(eventMap).forEach(function (key) {
                        if (props[key]) {
                            view.on(eventMap[key], props[key]);
                        }
                    });
                    resolve({ map: map_2, view: view });
                }).otherwise(function (err) {
                    reject(err);
                });
```

The last block of otherwise is causing the error, as it is not catching the promise to reject it back. I have found that in your pull request, but not moved to the release. Could you help us in using the WebScene?
