### ISSUE TITLE
Example of loading kml?

### ISSUE THREAD

**Issue by scottnc27603** [Esri/react-arcgis#68]
Is there an example of loading a kml file?  Or could someone suggest how I might load a kml file into a map?

**Comment by nicksenger** [comment]
@scottnc27603 this might be helpful: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-KMLLayer.html

In react-arcgis specifically, you would first get a reference to the `map` associated with a `<Map>` or `<Scene>` using either the `onLoad` handler or from props on a nested component, then you could attach the KML layer like in this example:

https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=layers-kml
