### ISSUE TITLE
README and demo update - componentWillMount() deprecation

### ISSUE THREAD

**Issue by andygup** [Esri/react-arcgis#80]
Just a heads-up, the README and demo app need to be updated. `componentWillMount()` is legacy and considered to be unsafe in the latest versions of react (I think 16.3 and greater)...`compomentDidMount()` is the replacement.

Reference: https://reactjs.org/docs/react-component.html#mounting

**Comment by jgravois** [comment]
pull requests welcome my dear amigo!

with @nicksenger gone we're going to need all the help we can get.

**Comment by jgravois** [comment]
resolved via #81. thank you @abdel-abdelrazek!
