### ISSUE TITLE
Update to Version 4.11

### ISSUE THREAD

**Issue by travisbutcher** [Esri/react-arcgis#86]
I am trying to update my version to 4.11,  I updated the esri-loader in the dependencies but still showing 4.10 as the version that is showing up.  I also trying to set the loader options but that did not seem to change it.  I am very interested in loading 4.11 to work with the Editor Widget in an application.

**Comment by tcatkins99** [comment]
You can just pass loaderOptions to your Map component. I'm doing it in my app and so far it's working as expected. I'm brand new to this component though so hopefully this is the right way to do it.

```
const loaderOptions = { url: `http://js.arcgis.com/4.11` };

<React.Fragment>
    <Helmet>
        <link rel="stylesheet" href="https://js.arcgis.com/4.11/esri/css/main.css" />
    </Helmet>
        <Map
            loaderOptions={loaderOptions}
        / >
    </AGOLTokenContext.Provider>
</React.Fragment>

```

**Comment by tomwayson** [comment]
I wonder why this is [pinned to a specific version of esri-loader](https://github.com/Esri/react-arcgis/blob/master/package.json#L9). We should probably update that to `^2.8.0`.

**Comment by travisbutcher** [comment]
looks like a previous issue https://github.com/Esri/react-arcgis/issues/75 locked the version.  Mine actually works now since I used the loader first for Identity before I load any map.

**Comment by tomwayson** [comment]
@travisbutcher a PR would be great.

I was talking to @jgravois about this, and we think that esri-loader should be a peer dependency of this library instead of a dependency. That way we could make the range very loose (I'm thinking `"esri-loader": "^2.0.0"`) and people can default to whatever version of the JSAPI they want by either specifying a specific minor version of esri-loader, or by passing `options`.

**Comment by schontz** [comment]
It would be good to put `loaderOptions` in the docs.

**Comment by gavinr** [comment]
I have created a PR to update to arcgis-js-api v4.12 and esri-loader `^2.10.0`: #98

Can a maintainer please move the [loaderOptions docs idea](https://github.com/Esri/react-arcgis/issues/86#issuecomment-512505831) and [peer dependency issue](https://github.com/Esri/react-arcgis/issues/86#issuecomment-481055198) to separate issues?

**Comment by gavinr** [comment]
Fun note: once this is updated to the latest `esri-loader`, you do not have to [load the js api stylesheet manually](https://user-images.githubusercontent.com/209355/61966982-c87cf400-af99-11e9-9e55-b139477da366.png) anymore, but can send it as part of the `loaderOptions` like here: https://github.com/gavinr/arcgis-js-api-extent-helper/blob/master/src/App.tsx#L36

**Comment by tomwayson** [comment]
Yeah, one of the things I've been wondering is should the next version use `{ css: true }` as the default loader options. I think so.

**Comment by mtrsklnkvMM** [comment]
I am having trouble changing the version of the API. I am trying loaderOptions to upgrade to 4.11 or 4.12, but I'm stuck with 4.10. I need to work with the Editor Widget too.
