### ISSUE TITLE
Question? How to display street names when using basemap as satelite.

### ISSUE THREAD

**Issue by nlmrkraju** [Esri/react-arcgis#93]
```JSX
                             <Map
                                mapProperties={{
                                    basemap: 'satelite',
                                    showLabels: true
                                }}
                                viewProperties=
                                {{
                                    center: [this.state.childData.y_COORDINATES, this.state.childData.x_COORDINATES],
                                    zoom: 16,
                                }}
                            >
                                <MapPointMarker longitude={this.state.childData.y_COORDINATES} latitude={this.state.childData.x_COORDINATES} />
                            </Map>

```
I can see street names in default basemap but not when the basemap is satelite.

![image](https://user-images.githubusercontent.com/51482867/59110329-e1a7e380-890c-11e9-9a65-c5e1b36ecafd.png)

![image](https://user-images.githubusercontent.com/51482867/59110593-77437300-890d-11e9-86f5-ffefbf6d2079.png)

**Comment by tomwayson** [comment]
Try `basemap: 'hybrid'`.

https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html#basemap

**Comment by nlmrkraju** [comment]
![image](https://user-images.githubusercontent.com/51482867/59198429-b79b2f00-8b61-11e9-859e-956ab6452c20.png)

Thanks for the suggestion. I changed basemap to hybrid, now it is showing place names but not street names as in default map.

**Comment by tomwayson** [comment]
Well, that's just how that basemap was designed and I'm not aware of any other built-in one that has street labels over imagery. There might be a custom basemap like that out there somewhere. You could ask that kind of question on [GeoNet](https://community.esri.com/).

FYI - I just noticed above that you include `showLabels: true` - I don't think that's a valid [map property](https://developers.arcgis.com/javascript/latest/api-reference/esri-Map.html#properties-summary).

**Comment by abdel-abdelrazek** [comment]
You can set basemap: "osm", and will show the street name.
![image](https://user-images.githubusercontent.com/38641993/60358056-3b974880-99a3-11e9-9a59-58f5db386742.png)
"

**Comment by nlmrkraju** [comment]
Hi @abdel-abdelrazek, thanks for your response. I don't see much differs between yours and my initial map in the question. I am looking for satellite view with street names on it.

**Comment by abdel-abdelrazek** [comment]
Hi @nlmrkraju , Actually there are a lot of differences between the two (--street direction, buildings names,..etc), just have another look.

Regarding to the satellite View, this setting **basemap: 'hybrid'** is the one that shows labels and other details -- without setting any other properties.
If the information it shows is not sufficient for you then **basemap: "osm"** is the most basemap that has information like labels and street names.
