### ISSUE TITLE
Uncaught TypeError: Xa is not a function

### ISSUE THREAD

**Issue by msicil** [Esri/react-arcgis#96]
Getting a dojo.js error when attempting to load any react component from the demo.  Sometimes the map still loads but not always.  Any idea what might cause this?

**Comment by agustin-pt** [comment]
Can you post the code?

**Comment by msicil** [comment]
```
import React from 'react';
import { Scene } from '@esri/react-arcgis';

export default (props) => (
	<Scene
		style={{ width: '100vw', height: '100vh' }}
		mapProperties={{ basemap: 'satellite' }}
		viewProperties={{
			center: [ -74.006, 40.7128 ],
			zoom: 100
		}}
	/>
);
```
The page loads, but I still get this error.  All I'm doing is importing this into a Switch on my main index page. Using react version 16.8.6

<img width="287" alt="Screenshot at Jun 26 15-27-46" src="https://user-images.githubusercontent.com/8879935/60208732-05cd5500-9827-11e9-977c-cf1451d6c384.png">

**Comment by msicil** [comment]
Issue disappeared after a refactor, definitely on my side
