### ISSUE TITLE
React native support?

### ISSUE THREAD

**Issue by thanmaic** [Esri/react-arcgis#97]
Hi,
Does this library support for **react-native** project as well?
I need to use esri maps in my project.

**Comment by tomwayson** [comment]
I doubt it. I don't know what it means for library to support react-native.

You could try and let us know.

Have you seen: https://www.npmjs.com/package/react-native-arcgis-mapview

**Comment by nicksenger** [comment]
@thanmaic react-arcgis, esri-loader, and the arcgis js api itself all rely on browser functionality that isn't available in react-native, so it won't work out of the box. I'd suggest looking at ArcGIS runtime SDKs for [android](https://developers.arcgis.com/android/) and [iOS](https://developers.arcgis.com/ios/).

If you really must use the JS API, you could make a map-centric web app and put it inside of a `WebView` component within your react-native app, but then any communication between your RN app and the map will need to be orchestrated using `postMessage`

**Comment by thanmaic** [comment]
Sure...thanks a lot
