### ISSUE TITLE
Advanced usage props and TypeScript

### ISSUE THREAD

**Issue by schontz** [Esri/react-arcgis#99]
I am trying to pass some props to something like the `BerumudaTriangle` component. Can I accomplish this without using `props: any`?. For example:

```JSX
// main.tsx
<Map>
  <BermudaTriangle something="foo" />
</Map>
```

```ts
// BermudaTriange.tsx
interface BermudaTriangleProps {
  map: __esri.Map;
  view: __esri.MapView;
  something: string;
});

const BermudaTriangle: React.FunctionComponent<BermudaTriangleProps> = ({ map, view, something }) => {
});
```

I get an error in `main.tsx` at `<BermudaTriangle something="foo" />`:

```
Type '{ something: string; }' is missing the following properties from type 'BermudaTriangleProps': view, map
```

`view`, and `map` are being passed implicitly, but TypeScript is not aware of that. Any advice?

**Comment by nicksenger** [comment]
Hi schnotz,

The `childrenAsFunction` prop was added to all Map and Scene components for this purpose in v3.3.2: https://github.com/Esri/react-arcgis/commit/40d3d975d357c1a6a02a63400c34e46116d9860b#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR6

It's not the cleanest solution but was done that way to avoid breaking changes. It would be cleaner to default to a render prop or even use hooks for this. Maybe something for a future major version change.

**Comment by schontz** [comment]
Ah. Interesting hack.

**Comment by tomwayson** [comment]
Closing as it looks like this is resolved.
